### ISSUE TITLE
Change icon

### ISSUE THREAD

**Issue by jenstornell** [lukaskleinschmidt/kirby-delete#2]
If it looks like the screenshot in the forum I suggest that you change the trash icon to not look exactly like the default trash link.

**Maybe invert it like this:**
http://fontawesome.io/icon/trash/

Maybe even make it red, the same color as the Panel delete warning.

**Comment by lukaskleinschmidt** [comment]
I will probably add a option for that so you can easily change the icon.
Personally I like that it does look exactly like the default link.
